### ISSUE TITLE
Rely on PSR instead of doctrine.

### ISSUE THREAD

**Issue by lyrixx** [IndraGunawan/api-rate-limit-bundle#1]
Hello.

in the readme, we can read:

> The service that is used to persist rate limit metadata. The service has to implement the Doctrine\Common\Cache\Cache interface. If no service id provided then the default storage is Filesystem (location: %kernel.cache_dir%/rate_limit).

IMHO, you should rely on a PSR/Cache interace instead of the doctrine one.
More over, in Symfony there is a DoctrineCacheAdapter.

ping @nicolas-grekas

**Comment by IndraGunawan** [comment]
nice idea,
so the configuration receive PSR/Cache implementation service id instead DoctrineCache right?
i will refactor to use PSR/Cache

**Comment by lyrixx** [comment]
Yes :-)

**Comment by IndraGunawan** [comment]
@lyrixx do you prefer PSR/Cache or PSR/SimpleCache?

**Comment by lyrixx** [comment]
Actually, I don't know. In symfony, we support both so ... :D It does not really matter I guess.

**Comment by nicolas-grekas** [comment]
Clearly PSR/Cache! That's the most flexible, and the one that is easily configurable with a few lines of yaml.
